version: '3.8'

services:

    dwity-universe-api:

        container_name: dwity-universe-api
        
        image: dwity-universe-api

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8888:8888"
